version: "3.9"

services:
  # Postgress
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
  
  # Redis
  redis:
    image: redis:7

  # Django Application
  web:
    build: .
    restart: always
    command: gunicorn shopapi.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - static:/code/static
      - media:/code/media
    depends_on:
      - redis
      - db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  
  # Celery 
  celery:
    build: .
    restart: always
    command: celery -A shopapi worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
  static:
  media: