# Generated by Django 4.1.7 on 2023-04-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
