# Generated by Django 4.1.7 on 2023-03-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_alter_address_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="discount",
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
