# Generated by Django 4.1.7 on 2023-03-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0003_alter_membership_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="image",
            field=models.ImageField(
                default="customer/images/default.jpg", upload_to="customer/images"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="discount",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
