# Generated by Django 4.1.7 on 2023-03-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="product/images/default.jpg", upload_to="product/images"
            ),
        ),
    ]
