# Generated by Django 4.1.7 on 2023-04-11 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
