# Generated by Django 4.1.7 on 2023-04-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_remove_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="product/images/default.jpg",
                help_text="Enter the product image",
                upload_to="product/images",
            ),
        ),
    ]
