# Generated by Django 4.1.7 on 2023-04-08 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_address",
            field=models.ForeignKey(
                default="now",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_order",
                to="customer.address",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                default="now",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipping_order",
                to="customer.address",
            ),
            preserve_default=False,
        ),
    ]
