# Generated by Django 4.1.7 on 2023-04-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
        ("order", "0002_delete_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ("-quantity",)},
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billed_orders",
                to="customer.address",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipped_orders",
                to="customer.address",
            ),
        ),
    ]
